module(name = "is-protoc-precompiled", version = "0.1.0")

bazel_dep(name = "protobuf", version = "36.0.bcr.1")
bazel_dep(name = "rules_cc", version = "0.2.22")
bazel_dep(name = "rules_java", version = "9.9.0")
bazel_dep(name = "rules_python", version = "2.3.2")

rules_python_config = use_extension("@rules_python//python/extensions:config.bzl", "config")
rules_python_config.explicit_init_py(default = True)
