load("@protobuf//bazel:cc_proto_library.bzl", "cc_proto_library")
load("@protobuf//bazel:java_proto_library.bzl", "java_proto_library")
load("@protobuf//bazel:proto_library.bzl", "proto_library")
load("@protobuf//bazel:py_proto_library.bzl", "py_proto_library")

proto_library(
    name = "my_proto",
    srcs = ["my_proto.proto"],
    visibility = ["//visibility:public"],
    deps = ["@protobuf//:any_proto"],
)

cc_proto_library(
    name = "my_proto_cc",
    visibility = ["//visibility:public"],
    deps = [":my_proto"],
)

java_proto_library(
    name = "my_proto_java",
    visibility = ["//visibility:public"],
    deps = [":my_proto"],
)

py_proto_library(
    name = "my_proto_py",
    visibility = ["//visibility:public"],
    deps = [":my_proto"],
)
